---
version: '3'
services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        ports:
            - "9050:9000"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "portainer_data:/data"
        networks:
            - easyform_net
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - "../volumes/pgdata_easyform:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: password
        networks:
            - easyform_net
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: always
        ports:
            - 80:80
        environment:
            PGADMIN_DEFAULT_EMAIL: easyform@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_ADDRESS: 0.0.0.0
            PGADMIN_PORT: 80
        volumes:
            - "../volumes/pgadmin_easyform:/var/lib/pgadmin4/storage"
        networks:
            - easyform_net
      
networks:
    easyform_net:
        driver: bridge

volumes:
    portainer_data: